// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4os7-QU5sxD4xJpdveK6xrThU81BW9y4',
    appId: '1:277690376322:web:a065c9bcce0f3b207dd49b',
    messagingSenderId: '277690376322',
    projectId: 'kolesterol-8a498',
    authDomain: 'kolesterol-8a498.firebaseapp.com',
    databaseURL: 'https://kolesterol-8a498-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kolesterol-8a498.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFx04M0RwP9Py3mWwIawg8bGqzzh4gNa0',
    appId: '1:277690376322:android:ca1d78fd3c5cdf257dd49b',
    messagingSenderId: '277690376322',
    projectId: 'kolesterol-8a498',
    databaseURL: 'https://kolesterol-8a498-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kolesterol-8a498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwD9hZlEO3se3-Ic9QQMhRxO7LsXhmHQ',
    appId: '1:277690376322:ios:727ab4afef3f3e727dd49b',
    messagingSenderId: '277690376322',
    projectId: 'kolesterol-8a498',
    databaseURL: 'https://kolesterol-8a498-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kolesterol-8a498.appspot.com',
    iosBundleId: 'com.example.kolestrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwD9hZlEO3se3-Ic9QQMhRxO7LsXhmHQ',
    appId: '1:277690376322:ios:727ab4afef3f3e727dd49b',
    messagingSenderId: '277690376322',
    projectId: 'kolesterol-8a498',
    databaseURL: 'https://kolesterol-8a498-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kolesterol-8a498.appspot.com',
    iosBundleId: 'com.example.kolestrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4os7-QU5sxD4xJpdveK6xrThU81BW9y4',
    appId: '1:277690376322:web:3e0eb9eda225d5d77dd49b',
    messagingSenderId: '277690376322',
    projectId: 'kolesterol-8a498',
    authDomain: 'kolesterol-8a498.firebaseapp.com',
    databaseURL: 'https://kolesterol-8a498-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kolesterol-8a498.appspot.com',
  );

}